apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: regcrd
      containers:
      - name: backend
        image: 0b6fa52889bf.ngrok.app/test/backend:v30
        ports:
        - containerPort: 80