apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: avoid
                operator: NotIn
                values:
                - "true"
      imagePullSecrets:
      - name: docker-hub
      containers:
      - name: backend
        image: nohhye/backend:v25
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "10.0.0.47"
        - name: DB_PORT
          value: "3000"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "shop_db"
        - name: JWT_SECRET
          value: "xptmxmxptmxm"
