apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: avoid
                operator: NotIn
                values:
                - "true"
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend
        image: 0b6fa52889bf.ngrok.app/cluster/frontend:v15
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "50m"
            memory: "50Mi"
          requests:
            cpu: "25m"
            memory: "25Mi"