apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: avoid
                operator: NotIn
                values:
                - "true"
      imagePullSecrets:
      - name: docker-hub
      containers:
      - name: frontend
        image: nohhye/frontend:v54
        ports:
        - containerPort: 80
